services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - sa

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASS}
    depends_on:
      - postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - sa

  ingress:
    image: nginx:stable-alpine
    ports:
      - "18080:80"
    volumes:
      - ./ingress:/etc/nginx/conf.d
    depends_on:
      - web
      - pgadmin
    networks:
      - sa

  web:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - ./frontend/cproom/:/app
    ports:
      - 3000:3000
    command: ["bun","dev"]
    networks:
      - sa

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./docker/backend-base/Dockerfile
  #   volumes:
  #     - ./backend:/app
  #   working_dir: /app
  #   command: ["air"]
  #   networks:
  #     - sa

  # minio:
  #   image: quay.io/minio/minio
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ROOT_USER}
  #     - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  #     - MINIO_BROWSER_REDIRECT_URL=http://localhost:18080/minio-console
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - ./data/minio:/data
  #   networks:
  #     - sa

networks:
  sa:
    driver: bridge