services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - sa

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASS}
    depends_on:
      - postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - sa

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - sa

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sa

  notification:
    build:
      context: .
      dockerfile: backend/services/notification/Dockerfile
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: notification_service
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      RABBITMQ_QUEUE_NAME: notifications
      RABBITMQ_EVENTS_QUEUE_NAME: notification_events
      NOTIFICATION_SERVICE_PORT: 8084
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8084:8084"
    networks:
      - sa

  ingress:
    image: nginx:stable-alpine
    ports:
      - "18080:80"
      - "${WEB_HTTPS_PORT:-3443}:443"
    volumes:
      - ./ingress:/etc/nginx/conf.d
      - ./backend/kong/certs:/etc/nginx/certs:ro
    depends_on:
      - web
      - pgadmin
    networks:
      - sa

  web:
    image: oven/bun:latest
    working_dir: /app
    volumes:
      - ./frontend/cproom/:/app
    ports:
      - 3000:3000
    command: ["bun","dev"]
    networks:
      - sa

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./docker/backend-base/Dockerfile
  #   volumes:
  #     - ./backend:/app
  #   working_dir: /app
  #   command: ["air"]
  #   networks:
  #     - sa

  # minio:
  #   image: quay.io/minio/minio
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ROOT_USER}
  #     - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  #     - MINIO_BROWSER_REDIRECT_URL=http://localhost:18080/minio-console
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - ./data/minio:/data
  #   networks:
  #     - sa

networks:
  sa:
    driver: bridge
