services:
  postgres:
    image: postgres:15
    container_name: postgres-cproom
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cproom_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./services/auth
    container_name: cproom-auth-service
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${AUTH_SERVICE_PORT}:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cproom_net

  booking-service:
    build: ./services/booking
    container_name: cproom-booking-service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      BOOKING_SERVICE_PORT: ${BOOKING_SERVICE_PORT}
    ports:
      - "${BOOKING_SERVICE_PORT}:50051"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cproom_net

  room-service:
    build: ./services/room
    container_name: cproom-room-service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      ROOM_SERVICE_PORT: ${ROOM_SERVICE_PORT}
    ports:
      - "${ROOM_SERVICE_PORT}:8082"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cproom_net
      
  approval-service:
    build: ./services/approval
    container_name: cproom-approval-service
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      APPROVAL_SERVICE_PORT: ${APPROVAL_SERVICE_PORT}
      APPROVAL_HTTP_PORT: ${APPROVAL_HTTP_PORT}
    ports:
      - "${APPROVAL_SERVICE_PORT}:50053"  # gRPC
      - "${APPROVAL_HTTP_PORT}:8083"      # HTTP health/test
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cproom_net

volumes:
  postgres_data:

networks:
  cproom_net:
