services:
  postgres:
    image: postgres:15
    container_name: postgres-cproom
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cproom_net

  auth-service:
    build: ./services/auth
    container_name: cproom-auth-service
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${AUTH_DB_NAME}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - cproom_net

volumes:
  postgres_data:

networks:
  cproom_net:
